# Generated by Django 2.1.5 on 2019-04-30 04:27

from django.db import migrations, models
import refs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('department_name', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('department_notes', models.CharField(blank=True, max_length=4000, verbose_name='Примечания')),
            ],
            options={
                'db_table': '"inventory"."Departments"',
                'ordering': ['department_region_id', 'department_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('employee_lastname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('employee_firstname', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('employee_middlename', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('employee_email', models.CharField(blank=True, max_length=150, verbose_name='email')),
                ('employee_phone_work', models.CharField(blank=True, max_length=50, verbose_name='тел.')),
                ('employee_note', models.TextField(blank=True, max_length=255, verbose_name='Примечание')),
                ('employee_full_fio', models.CharField(blank=True, max_length=150, verbose_name='ФИО польностью')),
                ('employee_is_chief', refs.models.CustomBooleanField(default=0, verbose_name='Руководитель')),
                ('employee_is_respons', refs.models.CustomBooleanField(default=0, verbose_name='Ответственный')),
                ('employee_is_mol', refs.models.CustomBooleanField(default=0, verbose_name='МО')),
            ],
            options={
                'db_table': '"inventory"."Employees"',
                'ordering': ['employee_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('houses_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('houses_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('houses_rem', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'db_table': '"inventory"."Houses"',
                'ordering': ['houses_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MCCat',
            fields=[
                ('wcat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('wcatname', models.CharField(max_length=255, verbose_name='Наименование')),
                ('wcatnotes', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'db_table': '"inventory"."Wealth_Categories"',
                'ordering': ['wcat_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MCType',
            fields=[
                ('wtype_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('wtype_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('wtype_notes', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'db_table': '"inventory"."Wealth_Types"',
                'ordering': ['wtype_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('office_name', models.CharField(max_length=255, verbose_name='Номер офиса')),
                ('office_notes', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Примечание')),
                ('office_is_store', refs.models.CustomBooleanField(default=0, verbose_name='Склад')),
            ],
            options={
                'db_table': '"inventory"."Offices"',
                'ordering': ['office_houses_id', 'office_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('position_name', models.CharField(max_length=255, verbose_name='Должность')),
                ('position_notes', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'db_table': '"inventory"."Positions"',
                'ordering': ['position_department_id', 'position_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('region_name', models.CharField(max_length=255, verbose_name='Наименование региона')),
            ],
            options={
                'db_table': '"inventory"."Region"',
                'ordering': ['region_id'],
                'managed': False,
            },
        ),
    ]
