# Generated by Django 2.1.5 on 2019-04-30 04:27

import catalog.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('whard_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('whard_inumber', models.CharField(max_length=30, verbose_name='Инв. номер')),
                ('whard_fnumber', models.CharField(blank=True, max_length=65, verbose_name='Заводской номер')),
                ('whard_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('whard_date_of_adoption', models.DateField(blank=True, verbose_name='Дата постановки на учет')),
                ('whard_initial_cost', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Начальная стоимость')),
                ('whard_residual_value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Остаточная стоимость')),
                ('whard_note', models.CharField(blank=True, max_length=65, verbose_name='Примечание')),
                ('whard_archiv', catalog.models.CustomBooleanField(verbose_name='Архив')),
            ],
            options={
                'db_table': '"inventory"."Wealth_Hardware"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelHardEmp',
            fields=[
                ('relhe_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
            ],
            options={
                'db_table': '"inventory"."Rel_Hardware_Employee"',
                'ordering': ['relhe_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelOfficeResp',
            fields=[
                ('roe_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
            ],
            options={
                'db_table': '"inventory"."Rel_Office_Respons_Employee"',
                'ordering': ['roe_id'],
                'managed': False,
            },
        ),
    ]
