# Generated by Django 2.1.5 on 2019-02-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('houses_id', models.IntegerField(primary_key=True, serialize=False)),
                ('houses_name', models.CharField(max_length=255)),
                ('houses_rem', models.CharField(max_length=255)),
                ('houses_region_id', models.IntegerField(default=54)),
            ],
            options={
                'db_table': 'Houses',
                'db_tablespace': 'inventory',
                'managed': False,
            },
        ),
    ]
