# Generated by Django 2.1.5 on 2019-02-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='houses',
            table='"inventory"."Houses"',
        ),
    ]
