# Generated by Django 2.1.5 on 2019-02-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190228_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('region_name', models.CharField(max_length=255, verbose_name='Наименование региона')),
            ],
            options={
                'db_table': '"inventory"."Region"',
                'managed': False,
            },
        ),
    ]
