# Generated by Django 2.1.5 on 2019-03-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=255)),
                ('office_notes', models.CharField(max_length=255)),
                ('office_is_store', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"inventory"."Offices"',
                'managed': False,
            },
        ),
    ]
