# Generated by Django 2.1.5 on 2019-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_offices'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('houses_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('houses_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('houses_rem', models.CharField(max_length=255, verbose_name='Примечание')),
            ],
            options={
                'db_table': '"inventory"."Houses"',
                'ordering': ['houses_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=255)),
                ('office_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('office_is_store', models.IntegerField(default=0)),
            ],
            options={
                'db_table': '"inventory"."Offices"',
                'managed': False,
            },
        ),
    ]
