# Generated by Django 2.1.5 on 2019-03-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190313_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'managed': False, 'ordering': ['employee_id']},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'managed': False, 'ordering': ['position_department_id', 'position_id']},
        ),
    ]
