# Generated by Django 2.1.5 on 2019-03-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190313_1102'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees',
            table='"inventory"."Employees"',
        ),
        migrations.AlterModelTable(
            name='position',
            table='"inventory"."Positions"',
        ),
    ]
