# Generated by Django 2.1.5 on 2019-03-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCCat',
            fields=[
                ('wcat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('wcatname', models.CharField(max_length=255, verbose_name='Наименование')),
                ('wcatnotes', models.CharField(max_length=255, verbose_name='Примечание')),
            ],
            options={
                'db_table': '"inventory"."Wealth_Categories"',
                'ordering': ['wcat_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MCType',
            fields=[
                ('wtype_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('wtype_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('wtype_notes', models.CharField(max_length=255, verbose_name='Примечание')),
            ],
            options={
                'db_table': '"inventory"."Wealth_Types"',
                'ordering': ['wtype_id'],
                'managed': False,
            },
        ),
    ]
