# Generated by Django 2.1.5 on 2019-03-15 09:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_mccat_mctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('whard_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Код')),
                ('whard_inumber', models.CharField(max_length=30, verbose_name='Инв. номер')),
                ('whard_fnumber', models.CharField(max_length=65, verbose_name='Заводской номер')),
                ('whard_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('whard_initial_cost', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0000'), max_digits=18, verbose_name='Начальная стоимость')),
                ('whard_residual_value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0000'), max_digits=18, verbose_name='Остаточная стоимость')),
                ('whard_note', models.CharField(max_length=65, verbose_name='Примечание')),
                ('whard_archiv', models.IntegerField(verbose_name='Архив')),
            ],
            options={
                'db_table': '"inventory"."Wealth_Hardware"',
                'ordering': ['whard_id'],
                'managed': False,
            },
        ),
    ]
